### ISSUE TITLE
Bug with String outputfileds in Mutation Builder

### ISSUE THREAD

**Issue by astanciu** [shahankit/custom-graphiql#2]
https://github.com/shahankit/custom-graphiql/blob/master/src/components/GenerateMutation.js#L211

If you have a mutation schema like this:

```
const DeleteThing = {
  type: graphql.GraphQLString,
  description: 'Delete a thing',
  args: {
    uuid: {
      name: 'Thing uuid',
      type: new graphql.GraphQLNonNull(graphql.GraphQLString)
    }
  },
  resolve: (stuff) => dostuff()
};
```
that line fails. `mutation.type` is ScalarType which does not have a getFields() method

**Comment by shahankit** [comment]
Fixed this issue in 2a41d9f2fb
