### ISSUE TITLE
Error when loading Saved queries

### ISSUE THREAD

**Issue by astanciu** [shahankit/custom-graphiql#3]
`Uncaught TypeError: Failed to construct 'URL': Invalid URL`
Happening on this line:
https://github.com/shahankit/custom-graphiql/blob/master/src/components/CustomGraphiQL.js#L117

My guess is something with the encoding of new lines. 

queryStringInput:
`"/graphql?query=%7B%0A%20%20requests%20%7B%0A%20%20%20%20uuid..."`

which decodes to:
`/graphql?query={?  requests {?    uuid...`

Not sure if those `?` belong.

**Comment by astanciu** [comment]
Nevermind, it's not the `?`... it's that the url is just a URI (missing "http://host.com"). Closing for now, but should prob check for this case, as the rest of Graphiql supports just the URI for fetching, etc...

**Comment by shahankit** [comment]
Okay so the input box should accept only valid url. A valid url regex check on provided string would be nice to have. I'll add it soon or feel free to open a pull request.
