### ISSUE TITLE
Upgrade graphiql

### ISSUE THREAD

**Issue by astanciu** [shahankit/custom-graphiql#7]
Can we upgrade graphiql to the latest version? The current version used here, 0.8.0, still uses the deprecated PropTypes.

**Comment by shahankit** [comment]
Hey @astanciu feel free to send me a pull request. Otherwise I'll update the version in few days.

**Comment by namnm** [comment]
Any news on this? This custom version of graphiql is awesome, I'm looking forward to your official updating, but seems you are pretty busy these days?

**Comment by astanciu** [comment]
Yeah, it's too bad. I've reverted to plain old GraphIQL... I tried upgrading this module, but for some reason, everything feels like a mess. I cannot get it to run at all :/

**Comment by shahankit** [comment]
Yeah I tried upgrading the module, it's giving some flow error. I don't have much time currently. I'll look into it and upgrade as soon as possible. Meanwhile feel free to send me a PR.

**Comment by astanciu** [comment]
Same... 
https://github.com/graphql/graphql-language-service/issues/111

I ended up using `ignore-loader` with
`{ test: /\.flow$/, loader: 'ignore-loader' }`

**Comment by shahankit** [comment]
@astanciu this is fixed now. All packages are upgraded to latest stable version.
